// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeriesScraper.Infrastructure.Data;

#nullable disable

namespace SeriesScraper.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SeriesScraper.Domain.Entities.ContentType", b =>
                {
                    b.Property<int>("ContentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("content_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ContentTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("ContentTypeId")
                        .HasName("pk_content_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_content_types_name");

                    b.ToTable("content_types", (string)null);

                    b.HasData(
                        new
                        {
                            ContentTypeId = 1,
                            Name = "TV Series"
                        },
                        new
                        {
                            ContentTypeId = 2,
                            Name = "Movie"
                        },
                        new
                        {
                            ContentTypeId = 3,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.DataSource", b =>
                {
                    b.Property<int>("SourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SourceId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("SourceId")
                        .HasName("pk_data_sources");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_data_sources_name");

                    b.ToTable("data_sources", (string)null);

                    b.HasData(
                        new
                        {
                            SourceId = 1,
                            Name = "IMDB"
                        });
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.DataSourceImportRun", b =>
                {
                    b.Property<int>("ImportRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("import_run_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImportRunId"));

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<long>("RowsImported")
                        .HasColumnType("bigint")
                        .HasColumnName("rows_imported");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("ImportRunId")
                        .HasName("pk_data_source_import_runs");

                    b.HasIndex("SourceId", "StartedAt")
                        .HasDatabaseName("IX_DataSourceImportRuns_SourceStarted");

                    b.ToTable("data_source_import_runs", (string)null);
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.Forum", b =>
                {
                    b.Property<int>("ForumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("forum_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ForumId"));

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_url");

                    b.Property<int>("CrawlDepth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("crawl_depth");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CredentialKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("credential_key");

                    b.Property<string>("EncryptedPassword")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("encrypted_password");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("PolitenessDelayMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(500)
                        .HasColumnName("politeness_delay_ms");

                    b.Property<string>("ResponseEncoding")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("utf-8")
                        .HasColumnName("response_encoding");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("ForumId")
                        .HasName("pk_forums");

                    b.ToTable("forums", (string)null);
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.ForumSection", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("section_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SectionId"));

                    b.Property<int?>("ContentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("content_type_id");

                    b.Property<string>("DetectedLanguage")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("detected_language");

                    b.Property<int>("ForumId")
                        .HasColumnType("integer")
                        .HasColumnName("forum_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastCrawledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_crawled_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentSectionId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_section_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("url");

                    b.HasKey("SectionId")
                        .HasName("pk_forum_sections");

                    b.HasIndex("ContentTypeId")
                        .HasDatabaseName("ix_forum_sections_content_type_id");

                    b.HasIndex("ForumId")
                        .HasDatabaseName("ix_forum_sections_forum_id");

                    b.HasIndex("ParentSectionId")
                        .HasDatabaseName("ix_forum_sections_parent_section_id");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasDatabaseName("ix_forum_sections_url");

                    b.ToTable("forum_sections", (string)null);
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.ImdbTitleAkasStaging", b =>
                {
                    b.Property<int>("StagingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("staging_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StagingId"));

                    b.Property<string>("Attributes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("attributes");

                    b.Property<bool>("IsOriginalTitle")
                        .HasColumnType("boolean")
                        .HasColumnName("is_original_title");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<int>("Ordering")
                        .HasColumnType("integer")
                        .HasColumnName("ordering");

                    b.Property<string>("Region")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("region");

                    b.Property<string>("Tconst")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tconst");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("title");

                    b.Property<string>("Types")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("types");

                    b.HasKey("StagingId")
                        .HasName("pk_imdb_title_akas_staging");

                    b.ToTable("imdb_title_akas_staging", (string)null);
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.ImdbTitleBasicsStaging", b =>
                {
                    b.Property<int>("StagingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("staging_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StagingId"));

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer")
                        .HasColumnName("end_year");

                    b.Property<string>("Genres")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("genres");

                    b.Property<bool>("IsAdult")
                        .HasColumnType("boolean")
                        .HasColumnName("is_adult");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("original_title");

                    b.Property<string>("PrimaryTitle")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("primary_title");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("runtime_minutes");

                    b.Property<int?>("StartYear")
                        .HasColumnType("integer")
                        .HasColumnName("start_year");

                    b.Property<string>("Tconst")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tconst");

                    b.Property<string>("TitleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title_type");

                    b.HasKey("StagingId")
                        .HasName("pk_imdb_title_basics_staging");

                    b.ToTable("imdb_title_basics_staging", (string)null);
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.ImdbTitleDetails", b =>
                {
                    b.Property<int>("MediaId")
                        .HasColumnType("integer")
                        .HasColumnName("media_id");

                    b.Property<string>("GenreString")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("genre_string");

                    b.Property<string>("Tconst")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tconst");

                    b.HasKey("MediaId")
                        .HasName("pk_imdb_title_details");

                    b.HasIndex("Tconst")
                        .IsUnique()
                        .HasDatabaseName("IX_ImdbTitleDetails_Tconst");

                    b.ToTable("imdb_title_details", (string)null);
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.ImdbTitleEpisodeStaging", b =>
                {
                    b.Property<int>("StagingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("staging_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StagingId"));

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("integer")
                        .HasColumnName("episode_number");

                    b.Property<string>("ParentTconst")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("parent_tconst");

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("integer")
                        .HasColumnName("season_number");

                    b.Property<string>("Tconst")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tconst");

                    b.HasKey("StagingId")
                        .HasName("pk_imdb_title_episode_staging");

                    b.ToTable("imdb_title_episode_staging", (string)null);
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.ImdbTitleRatingsStaging", b =>
                {
                    b.Property<int>("StagingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("staging_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StagingId"));

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("decimal(3,1)")
                        .HasColumnName("average_rating");

                    b.Property<int>("NumVotes")
                        .HasColumnType("integer")
                        .HasColumnName("num_votes");

                    b.Property<string>("Tconst")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tconst");

                    b.HasKey("StagingId")
                        .HasName("pk_imdb_title_ratings_staging");

                    b.ToTable("imdb_title_ratings_staging", (string)null);
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.Link", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("link_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LinkId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_current");

                    b.Property<int>("LinkTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("link_type_id");

                    b.Property<int?>("ParsedEpisode")
                        .HasColumnType("integer")
                        .HasColumnName("parsed_episode");

                    b.Property<int?>("ParsedSeason")
                        .HasColumnType("integer")
                        .HasColumnName("parsed_season");

                    b.Property<string>("PostUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("post_url");

                    b.Property<int>("RunId")
                        .HasColumnType("integer")
                        .HasColumnName("run_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("url");

                    b.HasKey("LinkId")
                        .HasName("pk_links");

                    b.HasIndex("LinkTypeId")
                        .HasDatabaseName("ix_links_link_type_id");

                    b.HasIndex("RunId", "PostUrl", "IsCurrent")
                        .HasDatabaseName("ix_links_run_id_post_url_is_current");

                    b.ToTable("links", (string)null);
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.LinkType", b =>
                {
                    b.Property<int>("LinkTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("link_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LinkTypeId"));

                    b.Property<string>("IconClass")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("icon_class");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("UrlPattern")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("url_pattern");

                    b.HasKey("LinkTypeId")
                        .HasName("pk_link_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_link_types_name");

                    b.ToTable("link_types", (string)null);

                    b.HasData(
                        new
                        {
                            LinkTypeId = 1,
                            IsActive = true,
                            IsSystem = true,
                            Name = "Direct HTTP",
                            UrlPattern = "^https?://"
                        },
                        new
                        {
                            LinkTypeId = 2,
                            IsActive = true,
                            IsSystem = true,
                            Name = "Torrent File",
                            UrlPattern = "\\.torrent$"
                        },
                        new
                        {
                            LinkTypeId = 3,
                            IsActive = true,
                            IsSystem = true,
                            Name = "Magnet URI",
                            UrlPattern = "^magnet:\\?"
                        },
                        new
                        {
                            LinkTypeId = 4,
                            IsActive = true,
                            IsSystem = true,
                            Name = "Cloud Storage URL",
                            UrlPattern = "(drive\\.google|dropbox|mega\\.nz)"
                        });
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.MediaEpisode", b =>
                {
                    b.Property<int>("EpisodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("episode_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EpisodeId"));

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("integer")
                        .HasColumnName("episode_number");

                    b.Property<int>("MediaId")
                        .HasColumnType("integer")
                        .HasColumnName("media_id");

                    b.Property<int>("Season")
                        .HasColumnType("integer")
                        .HasColumnName("season");

                    b.HasKey("EpisodeId")
                        .HasName("pk_media_episodes");

                    b.HasIndex("MediaId", "Season", "EpisodeNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_MediaEpisodes_MediaId_Season_Episode");

                    b.ToTable("media_episodes", (string)null);
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.MediaRating", b =>
                {
                    b.Property<int>("MediaId")
                        .HasColumnType("integer")
                        .HasColumnName("media_id");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<decimal>("Rating")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("rating");

                    b.Property<int>("VoteCount")
                        .HasColumnType("integer")
                        .HasColumnName("vote_count");

                    b.HasKey("MediaId", "SourceId")
                        .HasName("pk_media_ratings");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_media_ratings_source_id");

                    b.ToTable("media_ratings", (string)null);
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.MediaTitle", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("media_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MediaId"));

                    b.Property<string>("CanonicalTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("canonical_title");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("MediaId")
                        .HasName("pk_media_titles");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_media_titles_source_id");

                    b.HasIndex("CanonicalTitle", "Year", "Type")
                        .HasDatabaseName("IX_MediaTitles_TitleMatching");

                    b.ToTable("media_titles", (string)null);
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.MediaTitleAlias", b =>
                {
                    b.Property<int>("AliasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("alias_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AliasId"));

                    b.Property<string>("AliasTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("alias_title");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<int>("MediaId")
                        .HasColumnType("integer")
                        .HasColumnName("media_id");

                    b.Property<string>("Region")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("region");

                    b.HasKey("AliasId")
                        .HasName("pk_media_title_aliases");

                    b.HasIndex("AliasTitle")
                        .HasDatabaseName("IX_MediaTitleAliases_AliasTitle");

                    b.HasIndex("MediaId")
                        .HasDatabaseName("IX_MediaTitleAliases_MediaId");

                    b.ToTable("media_title_aliases", (string)null);
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.QualityLearnedPattern", b =>
                {
                    b.Property<int>("PatternId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pattern_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PatternId"));

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("algorithm_version");

                    b.Property<int>("DerivedRank")
                        .HasColumnType("integer")
                        .HasColumnName("derived_rank");

                    b.Property<int>("HitCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("hit_count");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastMatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_matched_at");

                    b.Property<string>("PatternRegex")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pattern_regex");

                    b.Property<string>("Polarity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("polarity");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.HasKey("PatternId")
                        .HasName("pk_quality_learned_patterns");

                    b.ToTable("quality_learned_patterns", (string)null);

                    b.HasData(
                        new
                        {
                            PatternId = 1,
                            AlgorithmVersion = "1.0",
                            DerivedRank = 100,
                            HitCount = 0,
                            IsActive = true,
                            PatternRegex = "\\b2160p\\b",
                            Polarity = "Positive",
                            Source = "Seed"
                        },
                        new
                        {
                            PatternId = 2,
                            AlgorithmVersion = "1.0",
                            DerivedRank = 100,
                            HitCount = 0,
                            IsActive = true,
                            PatternRegex = "\\b4K\\b",
                            Polarity = "Positive",
                            Source = "Seed"
                        },
                        new
                        {
                            PatternId = 3,
                            AlgorithmVersion = "1.0",
                            DerivedRank = 80,
                            HitCount = 0,
                            IsActive = true,
                            PatternRegex = "\\b1080p\\b",
                            Polarity = "Positive",
                            Source = "Seed"
                        },
                        new
                        {
                            PatternId = 4,
                            AlgorithmVersion = "1.0",
                            DerivedRank = 60,
                            HitCount = 0,
                            IsActive = true,
                            PatternRegex = "\\b720p\\b",
                            Polarity = "Positive",
                            Source = "Seed"
                        },
                        new
                        {
                            PatternId = 5,
                            AlgorithmVersion = "1.0",
                            DerivedRank = 70,
                            HitCount = 0,
                            IsActive = true,
                            PatternRegex = "\\bBluRay\\b",
                            Polarity = "Positive",
                            Source = "Seed"
                        },
                        new
                        {
                            PatternId = 6,
                            AlgorithmVersion = "1.0",
                            DerivedRank = 50,
                            HitCount = 0,
                            IsActive = true,
                            PatternRegex = "\\bWEB[-\\s]?DL\\b",
                            Polarity = "Positive",
                            Source = "Seed"
                        },
                        new
                        {
                            PatternId = 7,
                            AlgorithmVersion = "1.0",
                            DerivedRank = 65,
                            HitCount = 0,
                            IsActive = true,
                            PatternRegex = "\\bHEVC\\b",
                            Polarity = "Positive",
                            Source = "Seed"
                        },
                        new
                        {
                            PatternId = 8,
                            AlgorithmVersion = "1.0",
                            DerivedRank = 65,
                            HitCount = 0,
                            IsActive = true,
                            PatternRegex = "\\bx265\\b",
                            Polarity = "Positive",
                            Source = "Seed"
                        },
                        new
                        {
                            PatternId = 9,
                            AlgorithmVersion = "1.0",
                            DerivedRank = -10,
                            HitCount = 0,
                            IsActive = true,
                            PatternRegex = "\\bAI[-\\s]?upscale[d]?\\b",
                            Polarity = "Negative",
                            Source = "Seed"
                        });
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.QualityToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("token_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TokenId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Polarity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("polarity");

                    b.Property<int>("QualityRank")
                        .HasColumnType("integer")
                        .HasColumnName("quality_rank");

                    b.Property<string>("TokenText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("token_text");

                    b.HasKey("TokenId")
                        .HasName("pk_quality_tokens");

                    b.HasIndex("TokenText")
                        .IsUnique()
                        .HasDatabaseName("ix_quality_tokens_token_text");

                    b.ToTable("quality_tokens", (string)null);

                    b.HasData(
                        new
                        {
                            TokenId = 1,
                            IsActive = true,
                            Polarity = "Positive",
                            QualityRank = 100,
                            TokenText = "2160p"
                        },
                        new
                        {
                            TokenId = 2,
                            IsActive = true,
                            Polarity = "Positive",
                            QualityRank = 100,
                            TokenText = "4K"
                        },
                        new
                        {
                            TokenId = 3,
                            IsActive = true,
                            Polarity = "Positive",
                            QualityRank = 80,
                            TokenText = "1080p"
                        },
                        new
                        {
                            TokenId = 4,
                            IsActive = true,
                            Polarity = "Positive",
                            QualityRank = 60,
                            TokenText = "720p"
                        },
                        new
                        {
                            TokenId = 5,
                            IsActive = true,
                            Polarity = "Positive",
                            QualityRank = 40,
                            TokenText = "480p"
                        },
                        new
                        {
                            TokenId = 6,
                            IsActive = true,
                            Polarity = "Positive",
                            QualityRank = 70,
                            TokenText = "BluRay"
                        },
                        new
                        {
                            TokenId = 7,
                            IsActive = true,
                            Polarity = "Positive",
                            QualityRank = 50,
                            TokenText = "WEB-DL"
                        },
                        new
                        {
                            TokenId = 8,
                            IsActive = true,
                            Polarity = "Positive",
                            QualityRank = 65,
                            TokenText = "HEVC"
                        },
                        new
                        {
                            TokenId = 9,
                            IsActive = true,
                            Polarity = "Positive",
                            QualityRank = 65,
                            TokenText = "x265"
                        },
                        new
                        {
                            TokenId = 10,
                            IsActive = true,
                            Polarity = "Positive",
                            QualityRank = 60,
                            TokenText = "x264"
                        },
                        new
                        {
                            TokenId = 11,
                            IsActive = true,
                            Polarity = "Positive",
                            QualityRank = 75,
                            TokenText = "HDR"
                        },
                        new
                        {
                            TokenId = 12,
                            IsActive = true,
                            Polarity = "Positive",
                            QualityRank = 50,
                            TokenText = "SDR"
                        },
                        new
                        {
                            TokenId = 13,
                            IsActive = true,
                            Polarity = "Negative",
                            QualityRank = -10,
                            TokenText = "AI-upscaled"
                        },
                        new
                        {
                            TokenId = 14,
                            IsActive = true,
                            Polarity = "Negative",
                            QualityRank = -10,
                            TokenText = "AI upscale"
                        });
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.ScrapeRun", b =>
                {
                    b.Property<int>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("run_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RunId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int?>("ForumId")
                        .HasColumnType("integer")
                        .HasColumnName("forum_id");

                    b.Property<string>("ForumName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("forum_name");

                    b.Property<int>("ProcessedItems")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("processed_items");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("TotalItems")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_items");

                    b.HasKey("RunId")
                        .HasName("pk_scrape_runs");

                    b.HasIndex("ForumId")
                        .HasDatabaseName("ix_scrape_runs_forum_id");

                    b.ToTable("scrape_runs", (string)null);
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.ScrapeRunItem", b =>
                {
                    b.Property<int>("RunItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("run_item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RunItemId"));

                    b.Property<int?>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<string>("PostUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("post_url");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RunId")
                        .HasColumnType("integer")
                        .HasColumnName("run_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("RunItemId")
                        .HasName("pk_scrape_run_items");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_scrape_run_items_run_id");

                    b.HasIndex("RunId", "PostUrl")
                        .IsUnique()
                        .HasDatabaseName("ix_scrape_run_items_run_id_post_url");

                    b.ToTable("scrape_run_items", (string)null);
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_settings");

                    b.ToTable("settings", (string)null);

                    b.HasData(
                        new
                        {
                            Key = "ImdbRefreshIntervalHours",
                            Description = "Interval between IMDB dataset refreshes (hours)",
                            LastModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "24"
                        },
                        new
                        {
                            Key = "ForumStructureRefreshIntervalHours",
                            Description = "Interval between forum structure refreshes (hours)",
                            LastModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "24"
                        },
                        new
                        {
                            Key = "MaxConcurrentScrapeThreads",
                            Description = "Maximum number of concurrent scraping threads",
                            LastModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "1"
                        },
                        new
                        {
                            Key = "QualityPruningThreshold",
                            Description = "Patterns with hit_count below this are candidates for pruning",
                            LastModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "5"
                        },
                        new
                        {
                            Key = "ResultRetentionDays",
                            Description = "Days to retain results (0 = retain all)",
                            LastModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "0"
                        },
                        new
                        {
                            Key = "HttpRetryCount",
                            Description = "Number of HTTP request retries on failure",
                            LastModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "3"
                        },
                        new
                        {
                            Key = "HttpRetryBackoffMultiplier",
                            Description = "Backoff multiplier for HTTP retries",
                            LastModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "2"
                        },
                        new
                        {
                            Key = "HttpCircuitBreakerThreshold",
                            Description = "Failures before circuit breaker opens",
                            LastModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "5"
                        },
                        new
                        {
                            Key = "HttpTimeoutSeconds",
                            Description = "HTTP request timeout in seconds",
                            LastModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "30"
                        },
                        new
                        {
                            Key = "BulkImportMemoryCeilingMB",
                            Description = "Memory ceiling for bulk IMDB imports",
                            LastModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "256"
                        },
                        new
                        {
                            Key = "ForumRefreshIntervalHours",
                            Description = "Interval between forum structure refreshes (hours)",
                            LastModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "24"
                        },
                        new
                        {
                            Key = "scrape.request_delay",
                            Description = "Delay between scrape requests in milliseconds",
                            LastModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "2000"
                        },
                        new
                        {
                            Key = "results.page_size",
                            Description = "Number of results displayed per page",
                            LastModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "25"
                        },
                        new
                        {
                            Key = "forum.default_encoding",
                            Description = "Default character encoding for forum pages",
                            LastModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "windows-1250"
                        },
                        new
                        {
                            Key = "language.filter",
                            Description = "Language filter for results (all = no filter)",
                            LastModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "all"
                        },
                        new
                        {
                            Key = "imdb.refresh_interval",
                            Description = "Interval between IMDB dataset refreshes (hours, 168 = 7 days)",
                            LastModifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "168"
                        });
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.WatchlistItem", b =>
                {
                    b.Property<int>("WatchlistItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("watchlist_item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WatchlistItemId"));

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("custom_title");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastMatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_matched_at");

                    b.Property<int?>("MediaTitleId")
                        .HasColumnType("integer")
                        .HasColumnName("media_title_id");

                    b.Property<string>("NotificationPreference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("notification_preference");

                    b.HasKey("WatchlistItemId")
                        .HasName("pk_watchlist_items");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_WatchlistItems_IsActive");

                    b.HasIndex("MediaTitleId")
                        .HasDatabaseName("IX_WatchlistItems_MediaTitleId");

                    b.ToTable("watchlist_items", (string)null);
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.DataSourceImportRun", b =>
                {
                    b.HasOne("SeriesScraper.Domain.Entities.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_data_source_import_runs_data_sources_source_id");

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.ForumSection", b =>
                {
                    b.HasOne("SeriesScraper.Domain.Entities.ContentType", "ContentType")
                        .WithMany("Sections")
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_forum_sections_content_types_content_type_id");

                    b.HasOne("SeriesScraper.Domain.Entities.Forum", "Forum")
                        .WithMany("Sections")
                        .HasForeignKey("ForumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_forum_sections_forums_forum_id");

                    b.HasOne("SeriesScraper.Domain.Entities.ForumSection", "ParentSection")
                        .WithMany()
                        .HasForeignKey("ParentSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_forum_sections_forum_sections_parent_section_id");

                    b.Navigation("ContentType");

                    b.Navigation("Forum");

                    b.Navigation("ParentSection");
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.ImdbTitleDetails", b =>
                {
                    b.HasOne("SeriesScraper.Domain.Entities.MediaTitle", "MediaTitle")
                        .WithOne()
                        .HasForeignKey("SeriesScraper.Domain.Entities.ImdbTitleDetails", "MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_imdb_title_details_media_titles_media_id");

                    b.Navigation("MediaTitle");
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.Link", b =>
                {
                    b.HasOne("SeriesScraper.Domain.Entities.LinkType", "LinkType")
                        .WithMany("Links")
                        .HasForeignKey("LinkTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_links_link_types_link_type_id");

                    b.HasOne("SeriesScraper.Domain.Entities.ScrapeRun", "Run")
                        .WithMany("Links")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_links_scrape_runs_run_id");

                    b.Navigation("LinkType");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.MediaEpisode", b =>
                {
                    b.HasOne("SeriesScraper.Domain.Entities.MediaTitle", "MediaTitle")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_episodes_media_titles_media_id");

                    b.Navigation("MediaTitle");
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.MediaRating", b =>
                {
                    b.HasOne("SeriesScraper.Domain.Entities.MediaTitle", "MediaTitle")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_ratings_media_titles_media_id");

                    b.HasOne("SeriesScraper.Domain.Entities.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_media_ratings_data_sources_source_id");

                    b.Navigation("DataSource");

                    b.Navigation("MediaTitle");
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.MediaTitle", b =>
                {
                    b.HasOne("SeriesScraper.Domain.Entities.DataSource", "DataSource")
                        .WithMany("MediaTitles")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_media_titles_data_sources_source_id");

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.MediaTitleAlias", b =>
                {
                    b.HasOne("SeriesScraper.Domain.Entities.MediaTitle", "MediaTitle")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_title_aliases_media_titles_media_id");

                    b.Navigation("MediaTitle");
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.ScrapeRun", b =>
                {
                    b.HasOne("SeriesScraper.Domain.Entities.Forum", "Forum")
                        .WithMany("ScrapeRuns")
                        .HasForeignKey("ForumId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_scrape_runs_forums_forum_id");

                    b.Navigation("Forum");
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.ScrapeRunItem", b =>
                {
                    b.HasOne("SeriesScraper.Domain.Entities.ScrapeRun", "Run")
                        .WithMany("Items")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scrape_run_items_scrape_runs_run_id");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.WatchlistItem", b =>
                {
                    b.HasOne("SeriesScraper.Domain.Entities.MediaTitle", "MediaTitle")
                        .WithMany()
                        .HasForeignKey("MediaTitleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_watchlist_items_media_titles_media_title_id");

                    b.Navigation("MediaTitle");
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.ContentType", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.DataSource", b =>
                {
                    b.Navigation("MediaTitles");
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.Forum", b =>
                {
                    b.Navigation("ScrapeRuns");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.LinkType", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("SeriesScraper.Domain.Entities.ScrapeRun", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
